### ISSUE TITLE
Are we a spreadsheet interface yet?

### ISSUE THREAD

**Issue by johari** [johari/minicell#2]
- [x] Cells that contain numbers, strings, dates, names, amounts of money, etc.
- [x] Cells that contain formula that take other cells as an argument
- [x] In-place re-computation
- [ ] Formatted cells and content
- [x] Mixed-media (mainly plots, graphs, etc.)
