### ISSUE TITLE
COMET (frontend)

### ISSUE THREAD

**Issue by johari** [johari/minicell#28]
### Motivation

Many values change in the backend, but the frontend is not notified about these updates.

### Roadmap

- [x] (0.0.2)
    - [x] (Singe-user) Frontend calls `/minicell/all.json` after every write operation
- [ ] (0.0.3)
    - [ ] Receiving pings from WebSocket server to fetch `/minicell/all.json`
- [ ] (0.0.4)
    - [ ] Receiving payload through websocket, without a need to call `/minicell/all.json`

### What we currently do (Only pull)

Right now we re-fetch everything after each individual write to a cell. (Pull)

See `( ... , cometUpdateAll)` in line 396:

https://github.com/johari/minicell/blob/6b9b6d6c92359cfda031538c1d41c9222cd8c5f4/src/Spreadsheet.elm#L389-L396

### See also

* #33, which is a meta-issue for COMET support in backend
