### ISSUE TITLE
COMET (backend)

### ISSUE THREAD

**Issue by johari** [johari/minicell#33]
This is a meta-issue tracking everything we need from backend to support `Full COMET`.

### Roadmap

- [ ] (0.0.3)
    - [ ] Receiving pings from WebSocket server to fetch `/minicell/all.json`
- [ ] (0.0.4)
    - [ ] Receiving payload through websocket, without a need to call `/minicell/all.json`
    - [ ] (Multi-user) A websocket server will broadcast updates to each client

###  Backend

- [ ] Serving multiple clients via WebSocket
- [x] Needs to create a dependency tree (#39)
- [ ] Incrementally re-evaluate values
    - [ ] Cheap way is to just re-compute everything..
    - [ ] Expensive way is to think harder about incremental computation, specially for expensive graph computations

#### A more challenging example: Seconds since epoch

One extreme example is `=UNIXTIME()` changes value every second.

- [ ] **Pure pull:** (cheapest solution) to have the frontend fetch values periodically.
- [ ] **True comet:** Initial pull and then push from server 

Implementing this issue means we get much closer to a prototype of a collaborative graphsheet environment! :)

### Frontend

- [ ] If backend immediately return the list of affected cells after update (along with their values) then everything is easy.. It's just a matter of updating our comet registry inside the client in one go

### See also

* #28, which aims to address this in the frontend... (#28 might give some easier answers to this problem)
